### ISSUE TITLE
v0.1.3 hash table removed in v0.2.0?

### ISSUE THREAD

**Issue by shwestrick** [ocaml-multicore/lockfree#18]
The [`test_hash_multicore`](https://github.com/ocaml-bench/sandmark/blob/main/benchmarks/multicore-lockfree/test_hash_multicore.ml) sandmark benchmark uses a [hash table implementation from v0.1.3](https://github.com/ocaml-multicore/lockfree/blob/a3e6ed2c154decc5690cdd23f623251459fb12b8/src/lf_hash.ml) in this repo.

But, I see that in v0.2.0, this hash table implementation has been removed. Has that code been moved somewhere else? Or perhaps it's deprecated?

**Comment by Sudha247** [comment]
Hi @shwestrick, apologies for the delay in getting back to the query. We are currently re-evaluating the older implementations. They were done for a previous version of Multicore OCaml, and we want to make sure it's compliant with the memory model. A hash table implementation can be expected soon.

**Comment by shwestrick** [comment]
Okay sounds good! Thanks.
