### ISSUE TITLE
Suspicions of a data race (running the test suite with ThreadSanitizer generates a warning)

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml-multicore/lockfree#39]
In a joint effort with @fabbing, we built and ran the current testsuite at time of writing (revision https://github.com/ocaml-multicore/lockfree/commit/1df80e93c3e10e35178def215613eb079ecac80b) using the experimental [ThreadSanitizer race detection for OCaml](https://github.com/OlivierNicole/ocaml-tsan).

The runs resulted in a number of data race warnings (in 3 tests out of 5). The output of `dune runtest` is available here: https://gist.github.com/OlivierNicole/4cff8753b56c43d5c3a2de38b3868827

Some of these races may be benign, but the maintainers of the library are probably best placed to judge.

**Comment by OlivierNicole** [comment]
Running with the modifications proposed in #40 allows to get rid of a number of false positives and only one remaining data race is reported, between the two non-atomic (in the OCaml sense) accesses at
https://github.com/ocaml-multicore/lockfree/blob/1df80e93c3e10e35178def215613eb079ecac80b/src/ws_deque.ml#L131
and
https://github.com/ocaml-multicore/lockfree/blob/1df80e93c3e10e35178def215613eb079ecac80b/src/ws_deque.ml#L179

Full report with backtraces: https://gist.github.com/OlivierNicole/4f7a848579ce898a1e2fa95120223d9f

**Comment by lyrm** [comment]
So, there is a race, but an benign one. Here is a situation where the race happens:
- a stealer begins to steal a cell but stops just before performing the read (at line 179)
- another stealer steals this cell and performs  the following CAS that moves `top` forward.
- the producer fills the deque and circles back to the cell where the first stealer is still trying to steal. As `top` is one case after, the queue is not full and the producer can push.

In this situation, the producer and the stealer can respectfully write and read the same cell at the same time. However, as `top` has changed, the stealer will fail the following CAS operation and restart its operation, not using the possibly erroneous read value.

**Comment by OlivierNicole** [comment]
Good to know, thanks!
I’m closing this, but for future readers, TSan allows to suppress reports via supression files: https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions
Maybe in the future there will also be suppressions annotations that can be placed directly in the OCaml code.
