### ISSUE TITLE
Dscheck integration breaks utop 

### ISSUE THREAD

**Issue by bartoszmodelski** [ocaml-multicore/lockfree#44]
Current integration of dscheck breaks utop ([link](https://discuss.ocaml.org/t/ocaml-5-0-0-alpha1-utop-require-domainslib/10969)), and there does not seem to be a simple way to reconcile the two (per [limitations](https://dune.readthedocs.io/en/stable/variants.html)). Is there a different way to achieve the same separation (i.e. no dscheck shadowing in production code) without losing utop? 
 
- A ppx that will select implementation of `Atomic.*` depending on environment flag 
- A different way to do the shadowing? (cc @lyrm)

**Comment by Sudha247** [comment]
Can we make dscheck a `with-test` dependency? One need not install dscheck when installing lockfree then.

**Comment by bartoszmodelski** [comment]
We chatted during the multicore meeting: 

1. Using `with-test` dependency sounds good to resolve the issue above. Nonetheless, it turns out the current integration also causes problems with OCaml 4 compatiblity (https://github.com/ocaml-multicore/lockfree/pull/37#issuecomment-1351369115), and there was some other idea proposed to try out there (https://github.com/ocaml-multicore/lockfree/pull/37#issuecomment-1351687468), so we might want to coordinate here to find one hack to kill both birds. 

2. Another, possibly the simplest solution, would be to just use a dune rule to copy dscheck's atomic in testing.

**Comment by talex5** [comment]
Just to clarify, I have e.g.

- lib/mod.ml : uses `Atomic`
- test/dune : `(copy ../lib/mod.ml mod.ml)`
- test/atomic.ml  : `include Dscheck.TracedAtomic`

So mod.ml is compiled with the regular Atomic module in `lib`, and with `TracedAtomic` in `test`.

**Comment by lyrm** [comment]
Solved by #53.
