### ISSUE TITLE
Was this merged into domainslib?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-multicore/lockfree#51]
Which parts?

Thanks,
F.

**Comment by Sudha247** [comment]
`lockfree` in its current form is a separate library, independent of `domainslib`. In fact, `domainslib` uses `lockfree`'s work-stealing deque in its scheduler. `lockfree` is evolving into a nice collection of non-blocking concurrent data structures for OCaml 5, and we intend to keep it that way in the near future. `lockfree` is also available in opam-repository in case you want to use it.

**Comment by UnixJunkie** [comment]
ok, this is what I wanted to know: domainslib uses the "work-stealing deque" from here. Thanks.
