### ISSUE TITLE
Setup travis CI build

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/lockfree#7]
See https://github.com/ocaml-multicore/domainslib/ for example.

**Comment by Sudha247** [comment]
Domainslib has migrated to GitHub Actions CI. It might be easier to setup a GitHub Actions CI for lockfree too with `setup-ocaml`. (cf. https://github.com/ocaml-multicore/domainslib/blob/master/.github/workflows/main.yml)

**Comment by Sudha247** [comment]
Done in 310cebd893d881198d183c700540ed3935527405
